name: build-and-test

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: install requirements
        run: |
          pip install -r libs/dspace-rest-python/requirements.txt
          pip install -r requirements.txt

      - name: run smoketests
        run: |
          cd ./src
          python repo_import.py --help
