name: build-and-test

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: install requirements and run smoketests
        run: |
          echo Installing requirements
          python3 -m venv _gaenv && source _gaenv/bin/activate
          python3 -m pip install --upgrade setuptools six
          python3 -m pip install -r libs/dspace-rest-python/requirements.txt
          python3 -m pip install -r requirements.txt

          cd ./src
          python repo_import.py --help
